#!/bin/sh

VERSION=0.11

if [[ -d release ]];
then
  cd release
  svn export svn+ssh://ezra@dev.getsatisfaction.com/svn/sprinkles/trunk sprinkles-$VERSION
  markdown sprinkles-$VERSION/Satisfaction-lib-docs > sprinkles-$VERSION/Satisfaction-lib-docs.html
  tar czvf Sprinkles-$VERSION.tar.gz -T MANIFEST;
else
  echo "No release/ directory here; make one first.";
fi

