#!/bin/sh

VERSION=0.12
DIR=sprinkles-$VERSION

if [[ -d release ]];
then
  cd release
  svn export svn+ssh://ezra@dev.getsatisfaction.com/svn/sprinkles/trunk $DIR
  markdown $DIR/Satisfaction-lib-docs > $DIR/Satisfaction-lib-docs.html
  # cd $DIR
  perl -lpe '$_ = "'$DIR/'" . $_' $DIR/MANIFEST > /tmp/MANIFEST
  tar czvf ../Sprinkles-$VERSION.tar.gz -T /tmp/MANIFEST;
else
  echo "No release/ directory here; make one first.";
fi

